FROM rust:1.87 AS build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev cmake 

COPY ./backend/Cargo.toml ./backend/Cargo.toml
COPY ./backend/Cargo.lock ./backend/Cargo.lock
COPY ./backend/src ./backend/src

WORKDIR /app/backend

RUN cargo build --release

FROM rust:1.87-slim

COPY --from=build /app/backend/target/release/tx3-registry-backend /app/bin/tx3-registry-backend

ENV ROCKET_ADDRESS=0.0.0.0

WORKDIR /app/bin

CMD ["./tx3-registry-backend"]